dist: trusty
language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
before_script:
  - yarn build
deploy:
  provider: pages
  local-dir: build
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master